language: minimal

sudo: required

services:
  - docker

env:
  - ADDON="ICantBelieveItsNotValetudo"
  - ADDON="MaryTTS"
  - ADDON="picoTTS"

install:
  - export HADOLINT="${HOME}/hadolint"
  - sudo apt-get install jq
  - chmod +x .scripts/build.sh
  - curl -L -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.0/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}

before_script:
  - violations=$(${HADOLINT} $ADDON/Dockerfile | tee /dev/stderr | wc -l)
  - if [ $violations -gt 4 ]; then exit 2; fi

script:
  - ./.scripts/build.sh $ADDON 
