language: minimal

sudo: required

services:
  - docker

env:
  - ADDON="ICantBelieveItsNotValetudo"
  - ADDON="MaryTTS"
  - ADDON="picoTTS"

before_install:
  - sudo apt-get install jq
  - chmod +x .scripts/build.sh

script:
  - ./.scripts/build.sh $ADDON 
