name: Check PR
on:
  pull_request:
    branches:
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     addon: [
    #       "ICantBelieveItsNotValetudo"
    #       "MaryTTS"
    #       "picoTTS"
    #       "pigpio"
    #       "mpd"
    #       "valetudo-mapper"
    #       "ympd"
    #       "git-exporter"
    #       "syncthing"
    #       "OWASP-ZAP"
    #       "mitmproxy"
    #     ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: "*.sh"

  check-build:
    name: Check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ["mpd"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Detect chanced files
        id: files-check
        uses: dorny/paths-filter@v2.4.2
        with:
          list-files: json
          filters: |
            changed:
              - '**'
      - run: echo "${{ steps.files-check.outputs.changed_files }}"
      - if: contains( steps.files-check.outputs.changed_files, matrix.addon )
        run: echo "MPD changed"