name: Check PR
on:
  pull_request:
    branches:
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          pattern: "*.sh"

  check-build:
    name: Check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [
          "ICantBelieveItsNotValetudo",
          "MaryTTS",
          "picoTTS",
          "pigpio",
          "mpd",
          "valetudo-mapper",
          "ympd",
          "git-exporter",
          "syncthing",
          "OWASP-ZAP",
          "mitmproxy"
        ]
      fail-fast: false
    container:
      image: homeassistant/amd64-builder:7.2.0
      options: --rm --privileged
    steps:
      - name: Detect chanced files
        id: files-check
        uses: dorny/paths-filter@v2.4.2
        with:
          filters: |
            changed:
              - ${{matrix.addon}}/**

      - name: Checkout
        if: steps.files-check.outputs.changed == 'true'
        uses: actions/checkout@v2

      - name: Get config
        id: config
        if: steps.files-check.outputs.changed == 'true'
        shell: bash
        run: |
          IFS='/' read -r registry imagetemplate <<< "$(jq -r '.image' "${{ matrix.addon }}/config.json")"
          version=$(jq -r '.version' "${{ matrix.addon }}/config.json")
          archs=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | .] | join(" ")' "${{ matrix.addon }}/config.json")
          archs_param=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | "--" + .] | join(" ")' ${{ matrix.addon }}/config.json)

          echo "Docker Registry: $registry"
          echo "Imagetemplate: $imagetemplate"
          echo "Version: $version"
          echo "Architectures: $archs"

          echo "::set-output name=registry::$registry"        
          echo "::set-output name=imagetemplate::$imagetemplate"
          echo "::set-output name=version::$version"
          echo "::set-output name=archs_param::$archs_param"

      - name: Build addon
        if: steps.files-check.outputs.changed == 'true'
        run: >
          /usr/bin/builder.sh ${{ steps.config.outputs.archs_param }} 
          -t ${{ matrix.addon }} 
          -d ${{ steps.config.outputs.registry }} 
          -i ${{ steps.config.outputs.imagetemplate }}
          --test