name: Check PR
on:
  pull_request:
    branches:
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          pattern: "*.sh"

  check-build:
    name: Check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [
          "ICantBelieveItsNotValetudo",
          "MaryTTS",
          "picoTTS",
          "pigpio",
          "mpd",
          "valetudo-mapper",
          "ympd",
          "git-exporter",
          "syncthing",
          "OWASP-ZAP",
          "mitmproxy"
        ]
    container:
      image: homeassistant/amd64-builder:7.2.0
      options: --rm --privileged
    steps:
      - name: Detect chanced files
        id: files-check
        uses: dorny/paths-filter@v2.4.2
        with:
          list-files: json
          filters: |
            changed:
              - '**'
      - name: Checkout
        if: contains( steps.files-check.outputs.changed_files, matrix.addon )
        uses: actions/checkout@v2
      - name: Get config
        id: config
        run: |
          archs=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | .] | join(",")' "${{ matrix.addon }}/config.json")
          archs_param=$(jq -r '.arch // ["armv7", "armhf", "amd64", "aarch64", "i386"] | [.[] | "--" + .] | join(" ")' ${addon}/config.json)
          echo "Architectures: $archs"
          echo "::set-output name=archs_param::$archs_param"
      - name: Build addon
        if: contains( steps.files-check.outputs.changed_files, matrix.addon )
        run: /usr/bin/builder.sh ${{ stepts.config.outputs.archs_param }} -t ${{ matrix.addon }} --test