name: Lint / Syntax checks
on:
  pull_request:
    branches:
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run hadolint
        run: hadolint ./**/*Dockerfile

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.0.0

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .